version: '3.3'

services:
    db:
        image: postgres:12
        environment:
            POSTGRES_DB: knowcc
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume:/var/lib/postgresql/data
        networks:

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - postgres-adminer
        depends_on:
            - db

networks:
    postgres-adminer:

volumes:
    postgres-volume:
