version: '3.8'

services:
    gateway-service: 
        image: claudiapreda2307/gateway-service:init
        environment:
            BOOKS_SERVICE_API_ROUTE: books-service/api
            NODE_ENV: development
        ports:
            - 5000:80
        networks:
            - gateway-books
        depends_on:
            - books-service
    
    books-service: 
        image: claudiapreda2307/books-service:init
        environment:
            IO_SERVICE_API_ROUTE: io-service/api
            NODE_ENV: development
        networks:
            - gateway-books
            - books-io
        depends_on:
            - io-service
    
    io-service: 
        image: claudiapreda2307/io-service:init
        environment:
            PGUSER_FILE: db-user-secret
            PGPASSWORD_FILE: db-password-secret
            PGHOST: db
            PGPORT: 5432
            PGDATABASE: books
            NODE_ENV: staging
        secrets:
            - db-password-secret
            - db-user-secret
        networks:
            - books-io
            - io-postgres
        depends_on:
            - db
    
    db:
        image: postgres:12
        environment:
            POSTGRES_DB: books
            POSTGRES_USER_FILE: /run/secrets/db-user-secret
            POSTGRES_PASSWORD_FILE: /run/secrets/db-password-secret
        secrets:
            - db-password-secret
            - db-user-secret
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume:/var/lib/postgresql/data
        networks:            
            - io-postgres
            - postgres-adminer
    
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - postgres-adminer
        depends_on:
            - db

networks:
    gateway-books:
    books-io:
    io-postgres:
    postgres-adminer:

volumes:
    postgres-volume:
        
     
            

