version: '3.3'

services:
    # gateway-service:
    #     build: ./ApiGatewayMicroservice
    #     environment:
    #         BOOKS_SERVICE_API_ROUTE: books-service/api
    #         NODE_ENV: development
    #     ports:
    #         - 5000:3000
    #     networks:
    #         - gateway-books
    #     depends_on:
    #         - books-service

    # books-service:
    #     build: ./BooksMicroservice
    #     environment:
    #         IO_SERVICE_API_ROUTE: io-service/api
    #         NODE_ENV: development
    #     networks:
    #         - gateway-books
    #         - books-io
    #     depends_on:
    #         - io-service

    # io-service:
    #     build: ./IOMicroservice
    #     environment:
    #         PGUSER: admin
    #         PGPASSWORD: admin
    #         PGHOST: db
    #         PGPORT: 5432
    #         PGDATABASE: books
    #         NODE_ENV: development
    #     networks:
    #         - books-io
    #         - io-postgres

    #     depends_on:
    #         - db

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: knowcc
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume:/var/lib/postgresql/data
        networks:
            # - io-postgres
            - postgres-adminer

    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - postgres-adminer
        depends_on:
            - db

networks:
    # gateway-books:
    # books-io:
    # io-postgres:
    postgres-adminer:

volumes:
    postgres-volume:
