version: '3.3'

services:
    gateway-service:
        build: ./ApiGatewayMicroservice
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development
            AUTH_SERVICE_HOST: auth-service
            QUIZZES_SERVICE_HOST: quizzes-service
        # deploy:
        #     replicas: 3
        #     placement:
        #         max_replicas_per_node: 2
        #     update_config:
        #         parallelism: 2
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - frontend-gateway-net
            - backend-auth-net
        depends_on:
            - auth-service
            - quizzes-service

    auth-service:
        build: ./AuthMicroservice
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: db
            PGPORT: 5432
            PGDATABASE: knowcc
            NODE_ENV: development
        # deploy:
        #     replicas: 3
        #     placement:
        #         max_replicas_per_node: 2
        #     update_config:
        #         parallelism: 2
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - backend-auth-net
            - db-auth-net
    
    quizzes-service:
        build: ./QuizzesMicroservice
        environment:
            IO_SERVICE_HOST: io-service
            AUTH_SERVICE_HOST: auth-service
            NODE_ENV: development
        # deploy:
        #     replicas: 2
        #     placement:
        #         max_replicas_per_node: 1
        #     update_config:
        #         parallelism: 1
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - backend-io-net
            - backend-auth-net
        depends_on:
            - io-service
          
    io-service:
        build: ./IOMicroservice
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: db
            PGPORT: 5432
            PGDATABASE: knowcc
            NODE_ENV: development
        # deploy:
        #     replicas: 3
        #     placement:
        #         max_replicas_per_node: 2
        #     update_config:
        #         parallelism: 2
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - db-io-net
            - backend-io-net
        depends_on:
            - db

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: knowcc
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume:/var/lib/postgresql/data
        # deploy:
        #     placement:
        #         constraints: [node.role == manager]
        networks:
            - db-adminer-net
            - db-io-net
            - db-auth-net

    adminer:
        image: adminer
        ports:
            - 8080:8080
        # deploy:
        #     placement:
        #         constraints: [node.role == manager]
        depends_on:
            - db
            - gateway-service
        networks:
            - db-adminer-net
            - frontend-gateway-net
    
    frontend-service:
        build: ./FrontendMicroservice
        ports:
            - 8000:8000
        environment:
            NODE_ENV: development
            GATEWAY_SERVICE_HOST: localhost
        # deploy:
        #     replicas: 2
        #     placement:
        #         max_replicas_per_node: 1
        #     update_config:
        #         order: start-first
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - frontend-gateway-net
        depends_on:
            - gateway-service
    
networks:
    db-adminer-net:
    db-io-net:
    db-auth-net:
    backend-io-net:
    frontend-gateway-net:
    backend-auth-net:
volumes:
    postgres-volume:
