version: '3.3'

services:
    nginx:
        image: nginx:alpine
        volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
          - 80:80
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - internal
        depends_on:
            - frontend-service
            - adminer

    auth-service:
        image: claudiapreda2307/knowcc-auth:latest
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: knowcc-cluster_db
            PGPORT: 5432
            PGDATABASE: knowcc
            NODE_ENV: development
        # deploy:
        #     replicas: 3
        #     placement:
        #         max_replicas_per_node: 2
        #     update_config:
        #         parallelism: 2
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        depends_on:
            - db
        networks:
            - gateway-net
            - db-auth-net
    
    quizzes-service:
        image: claudiapreda2307/knowcc-quizzes:init
        environment:
            IO_SERVICE_HOST: knowcc-cluster_io-service
            AUTH_SERVICE_HOST: knowcc-cluster_auth-service
            NODE_ENV: development
        # deploy:
        #     replicas: 2
        #     placement:
        #         max_replicas_per_node: 1
        #     update_config:
        #         parallelism: 1
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - backend-io-net
            - gateway-net
        depends_on:
            - io-service
          
    io-service:
        image: claudiapreda2307/knowcc-io:init
        environment:
            PGUSER: admin
            PGPASSWORD: admin
            PGHOST: knowcc-cluster_db
            PGPORT: 5432
            PGDATABASE: knowcc
            NODE_ENV: development
        # deploy:
        #     replicas: 3
        #     placement:
        #         max_replicas_per_node: 2
        #     update_config:
        #         parallelism: 2
        #         delay: 10s
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - db-io-net
            - backend-io-net
        depends_on:
            - db

    db:
        image: postgres:12
        environment:
            POSTGRES_DB: knowcc
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        volumes:
            - ./Database/init-db.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume:/var/lib/postgresql/data
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - db-adminer-net
            - db-io-net
            - db-auth-net

    adminer:
        image: adminer
        deploy:
            placement:
                constraints: [node.role == manager]
        depends_on:
            - db
        networks:
            - db-adminer-net
            - internal
    
    frontend-service:
        image: claudiapreda2307/knowcc-frontend:init
        # ports:
        #     - 8000:8000
        environment:
            NODE_ENV: development
            REACT_APP_GATEWAY_SERVICE_HOST: 192.168.99.100
        # deploy:
        #     replicas: 2
        #     placement:
        #         max_replicas_per_node: 1
        #     update_config:
        #         order: start-first
        #     rollback_config:
        #         order: stop-first
        #     restart_policy:
        #         condition: on-failure
        networks:
            - internal
    
networks:
    db-adminer-net:
    db-io-net:
    db-auth-net:
    backend-io-net:
    internal:
    gateway-net:
volumes:
    postgres-volume:
